version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    command: >
      sh -c "npm install && npm run build && cp -r dist /usr/share/nginx/html"
    volumes:
      - ./dist:/usr/share/nginx/html:ro

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
